// Client name mapping utility
// Maps client IDs to their display names
// Based on seeded users from backend/prisma/seed.ts

export interface ClientInfo {
  id: string;
  name: string;
  email: string;
  company: string;
}

// Client ID to Client Info mapping (based on seeded data)
const CLIENTS_MAP: Record<string, ClientInfo> = {
  // These IDs are generated by Prisma during seeding
  // The actual IDs will be the ones created during database seeding
  'default-client': {
    id: 'default-client',
    name: 'Michael Anderson',
    email: 'client@demo.com',
    company: 'Anderson Creative Agency',
  },
  'default-boutique': {
    id: 'default-boutique',
    name: 'Sarah Chen',
    email: 'sarah@boutique.com',
    company: 'Lumen Boutique Design',
  },
};

// Function to get client name by ID
export const getClientName = (clientId: string): string => {
  const client = CLIENTS_MAP[clientId];
  return client ? client.name : `Client ${clientId.substring(0, 8)}...`;
};

// Function to get full client info by ID
export const getClientInfo = (clientId: string): ClientInfo | null => {
  return CLIENTS_MAP[clientId] || null;
};

// Function to get all available clients
export const getAllClients = (): ClientInfo[] => {
  return Object.values(CLIENTS_MAP);
};

// Function to format client display text
export const formatClientDisplay = (clientId: string): string => {
  const client = CLIENTS_MAP[clientId];
  if (client) {
    return `${client.name} (${client.company}`;
  }
  return getClientName(clientId);
};

export default {
  getClientName,
  getClientInfo,
  getAllClients,
  formatClientDisplay,
};
